
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armMotor1,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           armMotor2,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	bool slowModeOn = false;
	int motorSpeed = 127; //drive motor speed
	int motorSpeed2 = 80; //arm Motor speed
	bool slowButtonPressed = false;
	while(true){
		// Forwards
		if(vexRT[Ch2] > 15){
			motor[leftMotor] = motorSpeed;
			motor[rightMotor] = motorSpeed;
		} else
		// Backwards
		if(vexRT[Ch2] < -15){
			motor[leftMotor] = -motorSpeed;
			motor[rightMotor] = -motorSpeed;
		} else
		// Right
		if(vexRT[Ch1] > 15){
			motor[leftMotor] = motorSpeed;
			motor[rightMotor] = -motorSpeed;
		} else
			
		// Left
		if(vexRT[Ch1] < -15){
			motor[leftMotor] = -motorSpeed;
			motor[rightMotor] = motorSpeed;
		} 
		else {
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
		
		// Arm Motor Controls
		if(vexRT[Ch4] < -30) motor[armMotor1] = -motorSpeed2;
		else
		if(vexRT[Ch4] > 30) motor[armMotor1] = motorSpeed2;
		else motor[armMotor1]= 0;
		//Arm Motor going up
		if(vexRT[Ch3] > 30) {
			motor[armMotor2] = motorSpeed;
			motor[armMotor2] = motorSpeed;
		}
		else 
		//Arm Motor going down
		if(vexRT[Ch3] < -30) {
			motor[armMotor2] = -motorSpeed2;
			motor[armMotor2] = -motorSpeed2;
		}
		else motor[armMotor2] = 30;
		
		// Slowmode code
		if(vexRT[Btn6D] == 1 && slowButtonPressed == false) {slowModeOn = !slowModeOn; slowButtonPressed = true;}
		if(vexRT[Btn6D] == 0) slowButtonPressed = false;
		if(vexRT[Btn6U] == 1) slowModeOn = false;	
		
		// Reset slow mode
		if(slowModeOn == true) {motorSpeed = 60; motorSpeed2 = 50;}
		if(slowModeOn == false) {motorSpeed = 127; motorSpeed2 = 80;}
		}
}


