#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armMotor1,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           armMotor2,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Apply_Smoothing_Function(int x)
{
	// smoothing function applys correctly between 0-> 1 so we map the 0-127 down to 0-1
	x/= 127;
	// if X is less than 0 or a negative number
	// the absolute value of X is used to work properly, then flipped about the X axis to
	// match the appropriate orientation of the smoothing function
	
	// both outputs multiplied by 127 to undo the division applied at the start
	if(x<0) return -(200*abs(x)*0.0127) * (1/(1-(abs(x)*0.98))) * 127;
	// if its a positive number, just return the smoothing function normally
	return (200*x*0.0127) * (1/(1-(x*0.98))) * 127;
}

task main(){
	// define variables

	// left hand variables
	bool leftHandModeOn = false;
	bool leftHandButtonPressed = false;
	
	// control variables
	int forwardCtrl = vexRT[Ch2];
	int leftRightCtrl = vexRT[Ch1];
	int spinCtrl = vexRT[Ch4];
	int armUpDown = vexRT[Ch3];
	
	while(true){
		
		// left handed mode default is to have controls on right joystick
		if(vexRT[Btn7U] == 1 && leftHandButtonPressed == false) {leftHandModeOn = !leftHandModeOn; leftHandButtonPressed = true;}
		if(vexRT[Btn7U] == 0) leftHandButtonPressed = false;

		// set the control vars to the controller inputs.
		if(leftHandModeOn == true){
			forwardCtrl = vexRT[Ch3];
			leftRightCtrl = -vexRT[Ch4];
			spinCtrl = -vexRT[Ch1]/2;
			armUpDown = vexRT[Ch2];
		} else {
			forwardCtrl = vexRT[Ch2];
			leftRightCtrl = -vexRT[Ch1];
			spinCtrl = -vexRT[Ch4]/2;
			armUpDown = vexRT[Ch3];
		}
		
		// apply the smooting function
		forwardCtrl = Apply_Smoothing_Function(forwardCtrl);
		leftRightCtrl = Apply_Smoothing_Function(leftRightCtrl);
		spinCtrl = Apply_Smoothing_Function(spinCtrl);
		armUpDown = Apply_Smoothing_Function(armUpDown);

		// Driving Controls
		
		// reset to 0 every frame
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;

		//forward and backward
		motor[leftMotor] -= forwardCtrl;
		motor[rightMotor] -= forwardCtrl;

		// left and right
		motor[leftMotor] -= leftRightCtrl;
		motor[rightMotor] += leftRightCtrl;

		// arm Controls

		// reset arm motors to 0
		motor[armMotor1] = 0;
		motor[armMotor2] = 0;

		// spining
		if(abs(spinCtrl) > 45) motor[armMotor1] += spinCtrl;
		if(abs(armUpDown) > 45) motor[armMotor2] += armUpDown;
	}
}
